2024-12-31 19:17:53,338 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2024-12-31 19:17:54,094 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2024-12-31 19:17:54,307 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2024-12-31 19:18:06,385 - urllib3.connectionpool - DEBUG - https://oauth2.googleapis.com:443 "POST /token HTTP/11" 200 None
2024-12-31 19:18:06,400 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): www.googleapis.com:443
2024-12-31 19:54:20,622 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2024-12-31 19:54:21,910 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2024-12-31 19:54:22,135 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2024-12-31 19:55:35,899 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2024-12-31 19:55:36,045 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2024-12-31 19:55:36,052 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2024-12-31 20:02:29,597 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2024-12-31 20:02:29,838 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2024-12-31 20:02:29,847 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:18:24,819 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:18:25,304 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:18:25,358 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:18:25,485 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:18:25,486 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8F7820>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:18:25,487 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:18:25,489 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:18:25,490 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC8BD60>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:18:25,490 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:18:25,492 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:18:25,493 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8F7940>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:18:25,494 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:18:27,111 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:18:27,315 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:18:27,325 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:18:27,327 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:18:27,328 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8F7910>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:18:27,329 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:18:27,332 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:18:27,333 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ACF7EE0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:18:27,334 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:18:27,336 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:18:27,336 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC95550>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:18:27,337 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:22:34,674 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:22:34,902 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:22:34,910 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:22:34,911 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:22:34,912 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ACF7C40>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:22:34,913 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:22:34,915 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:22:34,916 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ACF8BE0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:22:34,917 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:22:34,919 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:22:34,920 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AD455E0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:22:34,921 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:24:52,375 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:24:52,695 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:24:52,702 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:24:52,704 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:24:52,705 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8E7040>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:24:52,706 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:24:52,708 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:24:52,709 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8B9BB0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:24:52,709 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:24:52,711 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:24:52,712 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8B9E50>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:24:52,713 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:24:54,146 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:24:54,331 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:24:54,353 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:24:54,355 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:24:54,355 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AA07B80>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:24:54,356 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:24:54,360 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:24:54,362 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AA22040>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:24:54,364 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:24:54,366 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:24:54,367 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8AE8B0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:24:54,368 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:25:08,799 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:25:08,948 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:25:08,956 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:25:08,958 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:25:08,959 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC87220>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:25:08,961 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:25:08,963 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:25:08,964 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A5C29D0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:25:08,965 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:25:08,967 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:25:08,968 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC87B20>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:25:08,969 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:25:09,976 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:25:10,189 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:25:10,200 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:25:10,202 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:25:10,202 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC9BBB0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:25:10,203 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:25:10,205 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:25:10,206 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC9BEE0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:25:10,207 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:25:10,209 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:25:10,213 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC9BC10>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:25:10,214 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:25:37,063 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:25:37,595 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:25:37,696 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:25:48,927 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:25:48,928 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC96C40>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:25:48,929 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:26:00,729 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:26:00,729 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ABB0220>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:26:00,730 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:26:11,930 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:26:11,930 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8B9100>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:26:11,931 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:26:38,869 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:26:39,348 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:26:39,376 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:26:51,555 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:26:51,557 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AB8CB50>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:26:51,557 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:27:03,600 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:03,602 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AA39BE0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:03,603 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:27:15,653 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:15,653 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AA39C10>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:15,654 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:27:17,330 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:17,585 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:27:17,594 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:27:17,597 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:17,598 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AB8C400>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:17,599 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:27:17,601 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:17,602 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AB8CE50>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:17,603 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:27:17,604 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:17,605 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AB8CE20>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:17,606 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:27:40,649 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:40,824 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:27:40,832 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:27:40,834 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:40,834 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC837C0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:40,835 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:27:40,837 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:40,838 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC834F0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:40,839 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:27:40,841 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:40,841 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC83850>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:40,842 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:27:42,278 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:42,480 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:27:42,492 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:27:42,494 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:42,495 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8DFE50>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:42,496 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:27:42,498 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:42,499 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AA39310>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:42,500 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:27:42,505 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:27:42,506 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ACD1CD0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:27:42,507 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:29:16,283 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:16,489 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:29:16,496 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:29:28,598 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:28,599 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ABA0550>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:29:28,600 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:29:28,602 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:28,603 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8C18B0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:29:28,604 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:29:28,606 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:28,607 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ACF8A60>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:29:28,608 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:29:29,899 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:30,112 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:29:30,122 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:29:30,124 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:30,125 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AA417F0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:29:30,126 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:29:30,128 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:30,129 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ABFD490>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:29:30,130 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:29:30,132 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:30,135 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ABFD6A0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:29:30,137 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:29:58,422 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:58,617 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:29:58,625 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:29:58,631 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:58,632 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC853A0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:29:58,633 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:29:58,637 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:58,638 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ABB01C0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:29:58,654 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:29:58,669 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:29:58,671 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39ABB0D90>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:29:58,672 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:31:03,495 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:31:03,645 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:31:03,652 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:31:15,700 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:31:15,700 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AB9ADF0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:31:15,701 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:31:15,703 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:31:15,704 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8E7D30>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:31:15,705 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:31:15,707 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:31:15,707 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A758B50>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:31:15,708 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
2025-01-02 14:31:16,904 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:31:22,215 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2025-01-02 14:31:22,223 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2025-01-02 14:31:34,353 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:31:34,354 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AC969A0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:31:34,355 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oauth2.googleapis.com:443
2025-01-02 14:31:34,370 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:31:34,371 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39AA1DB20>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:31:34,372 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oauth2.googleapis.com:443
2025-01-02 14:31:34,374 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/token'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2025-01-02 14:31:34,374 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B39A8AE130>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)")': /token
2025-01-02 14:31:34,375 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (4): oauth2.googleapis.com:443
